name: Nodes.js CI
 jobs:
  build:
    runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [20.x]
  steps:
  - name: Checkout repository
    uses: actions/setup-node@v3
  - name: Set up Node.s
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-verion }}
  - name: Install depenencies
    run: npm install
  = name: Start application
    run: npm start
